'use strict';
const $=id=>document.getElementById(id);
const themes=[{id:'love',name:'Aşk',symbol:'♡',subtitle:'Söylemekten hiç sıkılmadığın şeyler.',bg:'#f4c7d7',ink:'#792c50',title:'En sevdiğim iyi ki, sensin.'},{id:'birthday',name:'Doğum günü',symbol:'✷',subtitle:'İyi ki doğdun, iyi ki yollarımız kesişti.',bg:'#f4e6b8',ink:'#775c27',title:'Dünya seninle daha güzel.'},{id:'anniversary',name:'Yıl dönümü',symbol:'∞',subtitle:'Dünden bugüne, biriktirdiğiniz her şey.',bg:'#d9e6dc',ink:'#355a49',title:'Birlikte nice güzel günlere.'},{id:'valentine',name:'Sevgililer Günü',symbol:'♥',subtitle:'En güzel hikâyemin başrolüne.',bg:'#873653',ink:'#fff0f4',title:'Her gün, yeniden sen.'},{id:'promotion',name:'Terfi',symbol:'✧',subtitle:'Seninle gurur duyuyorum demenin yolu.',bg:'#e4dbf3',ink:'#60437e',title:'Seninle gurur duyuyorum.'},{id:'just',name:'İçimden geldi',symbol:'☀',subtitle:'Seni düşünmek için sebep gerekmiyor.',bg:'#f3d7c4',ink:'#8d5035',title:'Bugün aklıma sen geldin.'}];
const labels={postcard:'Kartpostal',text:'Şekilli not',photo:'Fotoğraf',song:'Şarkı'};
const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let box={theme:'love',recipient:'',sender:'',title:'',note:'',items:[]},editing=null,pendingPhoto='',busy=false,saveTimer,toastTimer,restored=false;
const newId=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
function spotifyLink(input){try{const u=new URL(input.trim());if(u.protocol!=='https:'||u.hostname!=='open.spotify.com')return null;const m=u.pathname.match(/^\/(?:intl-[a-z]{2}\/)?(track|album|playlist)\/([a-zA-Z0-9]{22})\/?$/);return m?{url:`https://open.spotify.com/${m[1]}/${m[2]}`,embed:`https://open.spotify.com/embed/${m[1]}/${m[2]}`} : null;}catch{return null;}}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3500);}
function validBox(data){if(!data||!themes.some(t=>t.id===data.theme)||!Array.isArray(data.items)||data.items.length>16)return false;return ['recipient','sender','title','note'].every(k=>typeof data[k]==='string')&&data.items.every(i=>i&&labels[i.type]&&typeof i.id==='string'&&(!i.photo||/^data:image\/(jpeg|png|webp);base64,[a-zA-Z0-9+/=]+$/.test(i.photo))&&(i.type!=='song'||spotifyLink(i.url)));}
try{const stored=JSON.parse(localStorage.getItem('sakli-box-v1')||'null');if(validBox(stored)){box=stored;restored=true;}}catch{}
function save(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem('sakli-box-v1',JSON.stringify(box));$('saveState').textContent='✓ Taslak bu tarayıcıda kaydedildi.';}catch{$('saveState').textContent='Tarayıcıya kaydedilemedi. Sayfayı kapatmadan kutunu indir.';}},250);}
function theme(){return themes.find(t=>t.id===box.theme)||themes[0];}
function applyTheme(){const t=theme();document.documentElement.style.setProperty('--soft',t.bg);document.documentElement.style.setProperty('--wine',t.id==='valentine'?'#873653':t.ink);$('themeTitle').textContent=t.name;$('themeBadge').textContent=t.symbol+' '+t.name;}
function show(view){for(const id of ['choose','editor','preview'])$(id).hidden=id!==view;window.scrollTo({top:0,behavior:'instant'});}
function openEditor(){applyTheme();for(const [id,key] of [['recipient','recipient'],['sender','sender'],['boxTitle','title'],['coverNote','note']])$(id).value=box[key];renderItems();show('editor');}
$('concepts').innerHTML=themes.map((t,i)=>`<button class="concept" data-theme="${t.id}" style="--tile:${t.bg};--tileink:${t.ink}"><span class="symbol" aria-hidden="true">${t.symbol}</span><span class="number">0${i+1}</span><h3>${t.name}</h3><p>${t.subtitle}</p><span class="arrow" aria-hidden="true">↗</span></button>`).join('');
$('concepts').onclick=e=>{const b=e.target.closest('[data-theme]');if(!b)return;const previous=theme();box.theme=b.dataset.theme;if(!box.title||box.title===previous.title)box.title=theme().title;save();openEditor();};
$('myDraft').onclick=()=>{if(!box.title)box.title=theme().title;openEditor();};$('myDraft').textContent=restored?'Taslağıma dön ↗':'Kutuma başla ↗';$('backConcept').onclick=()=>show('choose');
for(const [id,key] of [['recipient','recipient'],['sender','sender'],['boxTitle','title'],['coverNote','note']])$(id).oninput=e=>{box[key]=e.target.value;save();};
function memoryMarkup(item,gift=false){const title=escapeHTML(item.title),text=escapeHTML(item.text);let content='';if(item.type==='postcard')content=`<span class="stamp" aria-hidden="true">${theme().symbol}</span><h3>${title}</h3><p>${text}</p>`;if(item.type==='text')content=`<div class="shape"><p>${text}</p></div>`;if(item.type==='photo')content=`<img src="${escapeHTML(item.photo)}" alt="${title||'Birlikte bir anı'}"><p>${title}</p>`;if(item.type==='song')content=`<span class="musicicon" aria-hidden="true">♫</span><small>BİZİM ŞARKIMIZ</small><h3>${title||'Sana bir şarkı'}</h3><p>${text}</p>${gift?`<button class="spotify-open" data-spotify="${escapeHTML(spotifyLink(item.url)?.embed||'')}">Spotify'da dinle ▶</button>`:''}`;return `<div class="memory-body">${content}</div>`;}
function renderItems(){$('itemCount').textContent=box.items.length+' anı';$('items').innerHTML=box.items.length?box.items.map((item,i)=>`<article class="memory ${item.type} ${['heart','circle','wave'].includes(item.shape)?item.shape:''}"><button class="card-open" data-edit="${item.id}" aria-label="${escapeHTML(labels[item.type])} düzenle">${memoryMarkup(item)}</button><div class="cardfoot"><span>${String(i+1).padStart(2,'0')} / ${labels[item.type]}</span><div class="cardactions"><button data-move="${item.id}" data-dir="-1" ${i===0?'disabled':''} aria-label="Anıyı önceye taşı">←</button><button data-move="${item.id}" data-dir="1" ${i===box.items.length-1?'disabled':''} aria-label="Anıyı sonraya taşı">→</button><button data-delete="${item.id}" aria-label="Anıyı kaldır">×</button></div></div></article>`).join(''):'<div class="empty"><span>♡</span><h3>İlk anıyla başlasın.</h3><p>Yukarıdan bir kartpostal, not, fotoğraf veya şarkı ekle.</p></div>';}
$('items').onclick=e=>{const edit=e.target.closest('[data-edit]'),move=e.target.closest('[data-move]'),del=e.target.closest('[data-delete]');if(edit)return openItem(box.items.find(i=>i.id===edit.dataset.edit));if(move){const from=box.items.findIndex(i=>i.id===move.dataset.move),to=from+Number(move.dataset.dir);if(to>=0&&to<box.items.length){[box.items[from],box.items[to]]=[box.items[to],box.items[from]];renderItems();save();}}if(del){box.items=box.items.filter(i=>i.id!==del.dataset.delete);renderItems();save();toast('Anı kutudan kaldırıldı.');}};
document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{if(box.items.length>=16)return toast('Bir kutuya en fazla 16 anı ekleyebilirsin.');openItem({id:newId(),type:b.dataset.add,title:'',text:'',shape:'heart',url:'',photo:''},true);});
function openItem(item,isNew=false){editing={...item,isNew};pendingPhoto=item.photo||'';$('dialogTitle').textContent=labels[item.type]+(isNew?' ekle':' düzenle');$('formError').textContent='';$('saveItem').textContent=isNew?'Kutuya ekle ♡':'Değişiklikleri kaydet';let fields='';if(['postcard','song'].includes(item.type))fields+=`<label>${item.type==='song'?'Şarkının adı':'Kartın başlığı'}<input id="itemTitle" maxlength="80" value="${escapeHTML(item.title)}" placeholder="${item.type==='song'?'Bize hep o günü hatırlatan şarkı':'Sende en sevdiğim şey…'}" required></label>`;if(item.type==='photo')fields+=`<label>Bir fotoğraf seç<input id="itemPhoto" type="file" accept="image/jpeg,image/png,image/webp,image/avif" ${pendingPhoto?'':'required'}></label><p class="dialoghint">JPG, PNG, WebP veya AVIF · En fazla 12 MB. Fotoğraf kutuya uygun boyuta küçültülür.</p><img class="uploadpreview" id="photoPreview" ${pendingPhoto?`src="${escapeHTML(pendingPhoto)}"`:'hidden'} alt="Seçilen fotoğraf"><label>Altına bir not<input id="itemTitle" maxlength="100" value="${escapeHTML(item.title)}" placeholder="O gün hiç bitmesin istemiştim."></label>`;if(item.type==='text')fields+=`<label>Yazının şekli<select id="itemShape"><option value="heart">Yumuşak kalp</option><option value="circle">Yuvarlak</option><option value="wave">Dalga</option></select></label>`;if(item.type!=='photo')fields+=`<label>${item.type==='song'?'Bu şarkı neden burada?':'İçinden geçenler'}<textarea id="itemText" rows="4" maxlength="${item.type==='text'?180:700}" placeholder="Sadece senin söyleyebileceğin bir şey yaz…" ${item.type==='song'?'':'required'}>${escapeHTML(item.text)}</textarea></label>`;if(item.type==='song')fields+=`<label>Spotify bağlantısı<input id="itemUrl" type="url" value="${escapeHTML(item.url)}" placeholder="https://open.spotify.com/track/…" required></label><p class="dialoghint">Spotify’da şarkı → Paylaş → Bağlantıyı kopyala. Şarkı, albüm ve çalma listesi bağlantıları desteklenir. Çalma süresi Spotify hesabına ve bölgeye bağlı olabilir.</p>`;$('itemFields').innerHTML=fields;if(item.type==='text')$('itemShape').value=item.shape||'heart';if(item.type==='photo')$('itemPhoto').onchange=readPhoto;$('itemDialog').showModal();}
async function readPhoto(e){const file=e.target.files[0];if(!file)return;const session=editing;busy=true;$('saveItem').disabled=true;$('formError').textContent='Fotoğraf hazırlanıyor…';let url;try{if(!['image/jpeg','image/png','image/webp','image/avif'].includes(file.type)||file.size>12*1024*1024)throw Error('12 MB altında bir JPG, PNG, WebP veya AVIF seç.');url=URL.createObjectURL(file);const img=new Image();img.src=url;await img.decode();if(img.naturalWidth*img.naturalHeight>50e6)throw Error('Fotoğraf çok büyük. Daha küçük bir görsel seç.');const scale=Math.min(1,1400/Math.max(img.naturalWidth,img.naturalHeight)),c=document.createElement('canvas');c.width=Math.round(img.naturalWidth*scale);c.height=Math.round(img.naturalHeight*scale);const context=c.getContext('2d');context.fillStyle='#fff';context.fillRect(0,0,c.width,c.height);context.drawImage(img,0,0,c.width,c.height);if(editing!==session)return;pendingPhoto=c.toDataURL('image/jpeg',.8);$('photoPreview').src=pendingPhoto;$('photoPreview').hidden=false;$('formError').textContent='';}catch(error){if(editing===session){$('formError').textContent=error.message||'Fotoğraf açılamadı.';e.target.value='';}}finally{if(url)URL.revokeObjectURL(url);if(editing===session){busy=false;$('saveItem').disabled=false;}}}
function closeItem(){editing=null;busy=false;$('saveItem').disabled=false;$('itemDialog').close();}for(const id of ['closeDialog','cancelDialog'])$(id).onclick=closeItem;$('itemDialog').addEventListener('cancel',()=>{editing=null;busy=false;$('saveItem').disabled=false;});
$('itemForm').onsubmit=e=>{e.preventDefault();if(busy||!editing)return;const item={id:editing.id,type:editing.type,title:$('itemTitle')?.value.trim()||'',text:$('itemText')?.value.trim()||'',shape:$('itemShape')?.value||'heart',photo:pendingPhoto,url:''};if(item.type==='photo'&&!pendingPhoto){$('formError').textContent='Önce bir fotoğraf seç.';return;}if(['postcard','text'].includes(item.type)&&!item.text){$('formError').textContent='Anın için birkaç kelime yaz.';return;}if(item.type==='song'){const link=spotifyLink($('itemUrl').value);if(!link){$('formError').textContent='Geçerli bir open.spotify.com şarkı, albüm veya çalma listesi bağlantısı gir.';return;}item.url=link.url;}if(editing.isNew)box.items.push(item);else{const index=box.items.findIndex(i=>i.id===item.id);if(index>=0)box.items[index]=item;}save();renderItems();closeItem();toast('Anın kutudaki yerini aldı. ♡');};
function giftMarkup(){return `<div class="gift-shell"><div class="gift-to">${escapeHTML(box.recipient||'Sevdiğime')} için, sevgiyle</div><h1>${escapeHTML(box.title||theme().title)}</h1><p class="gift-note">${escapeHTML(box.note||'Bu kutuda biraz biz varız. İyi ki.')}</p><p class="gift-sign">Sevgiyle, ${escapeHTML(box.sender||'seni seven biri')}</p><button class="seal" data-open-gift aria-label="Anı kutusunu aç">♡</button><p class="opentext">KALBE DOKUN, KUTUYU AÇ</p><div class="gift-items" hidden>${box.items.map(item=>`<article class="memory ${item.type} ${['heart','circle','wave'].includes(item.shape)?item.shape:''}">${memoryMarkup(item,true)}</article>`).join('')}</div><p class="receipt" hidden>Hepsi bir yana, iyi ki sen. ♡</p></div>`;}
function giftClick(e){const open=e.target.closest('[data-open-gift]');if(open){const shell=open.closest('.gift-shell');shell.querySelector('.gift-items').hidden=false;shell.querySelector('.receipt').hidden=false;shell.querySelector('.opentext').hidden=true;open.hidden=true;return;}const play=e.target.closest('[data-spotify]');if(play){const src=play.dataset.spotify;if(!/^https:\/\/open\.spotify\.com\/embed\/(track|album|playlist)\/[a-zA-Z0-9]{22}$/.test(src))return;const frame=document.createElement('iframe');frame.title='Spotify şarkı oynatıcı';frame.src=src;frame.allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture';frame.loading='lazy';play.replaceWith(frame);}}
$('giftPreview').onclick=giftClick;$('previewButton').onclick=()=>{if(!box.items.length)return toast('Önce kutuya en az bir anı ekle.');$('giftPreview').innerHTML=giftMarkup();show('preview');};$('backEditor').onclick=()=>show('editor');
$('download').onclick=async()=>{const button=$('download');button.disabled=true;try{const response=await fetch('style.css?v=1');if(!response.ok)throw Error('İndirme hazırlanamadı.');const css=await response.text(),t=theme();const source='<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+escapeHTML(box.title)+'</title><style>'+css+'\n:root{--soft:'+t.bg+';--wine:'+(t.id==='valentine'?'#873653':t.ink)+'}body{padding:25px;max-width:1000px;margin:auto}.gift-shell{min-height:85svh}@media(max-width:600px){body{padding:12px}}</style></head><body>'+giftMarkup()+'<script>document.addEventListener("click",'+giftClick.toString()+');<\/script></body></html>';const blob=new Blob([source],{type:'text/html;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='sana-sakli-bir-kutu.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('Kutun indirildi. Dosyayı sevdiğine gönderebilirsin.');}catch{toast('İndirme hazırlanamadı. Bağlantını kontrol edip tekrar dene.');}finally{button.disabled=false;}};

