'use strict';
if(location.hostname.endsWith('.github.io'))location.replace('https://saklianikutusu.berkantkul.com.tr/');
const $=id=>document.getElementById(id);
const themes=[{id:'love',name:'Aşk',symbol:'♡',subtitle:'Söylemekten hiç sıkılmadığın şeyler.',bg:'#f4c7d7',ink:'#792c50',title:'En sevdiğim iyi ki, sensin.'},{id:'birthday',name:'Doğum günü',symbol:'✷',subtitle:'İyi ki doğdun, iyi ki yollarımız kesişti.',bg:'#f4e6b8',ink:'#775c27',title:'Dünya seninle daha güzel.'},{id:'anniversary',name:'Yıl dönümü',symbol:'∞',subtitle:'Dünden bugüne, biriktirdiğiniz her şey.',bg:'#d9e6dc',ink:'#355a49',title:'Birlikte nice güzel günlere.'},{id:'valentine',name:'Sevgililer Günü',symbol:'♥',subtitle:'En güzel hikâyemin başrolüne.',bg:'#873653',ink:'#fff0f4',title:'Her gün, yeniden sen.'},{id:'promotion',name:'Terfi',symbol:'✧',subtitle:'Seninle gurur duyuyorum demenin yolu.',bg:'#e4dbf3',ink:'#60437e',title:'Seninle gurur duyuyorum.'},{id:'just',name:'İçimden geldi',symbol:'☀',subtitle:'Seni düşünmek için sebep gerekmiyor.',bg:'#f3d7c4',ink:'#8d5035',title:'Bugün aklıma sen geldin.'},{id:'special',name:'Özel',symbol:'✦',subtitle:'Başka hiçbir başlığa sığmayan hikâyen için.',bg:'#dce6f2',ink:'#405b78',title:'Tamamen sana özel.'}];
const labels={postcard:'Kartpostal',text:'Şekilli not',photo:'Fotoğraf',song:'Şarkı'};
const palettes={theme:{name:'Konsept',soft:null,wine:null},rose:{name:'Gül',soft:'#f4d3df',wine:'#79304f'},sun:{name:'Gün ışığı',soft:'#f6eccb',wine:'#715b2c'},sky:{name:'Gökyüzü',soft:'#dcecf3',wine:'#31556e'},night:{name:'Gece',soft:'#dedff1',wine:'#4d4778'}};
const styleDefaults={palette:'theme',icon:'♡',font:'romantic',layout:'collage',effect:'hearts'};
const ideaBank={love:{postcard:['Sende en sevdiğim şey…','Yanında kendim olabildiğim için iyi ki varsın.'],text:['Seninle sıradan günler bile hatıraya dönüşüyor.'],photo:['Bu ana dönüp dönüp bakmak istiyorum.'],song:['Bizim şarkımız','Ne zaman duysam aklıma sen geliyorsun.']},birthday:{postcard:['Dünya seninle daha güzel.','Yeni yaşın kalbin kadar güzel olsun. İyi ki doğdun!'],text:['İyi ki doğdun, iyi ki yollarımız kesişti.'],photo:['Yeni yaşına en sevdiğim anımızdan bir kare.'],song:['Bugünün şarkısı','Bu şarkı yeni yaşının fon müziği olsun.']},anniversary:{postcard:['Birlikte nice yıllara.','Geçen her yıl, seni seçmek için yeni bir sebep verdi.'],text:['Dün, bugün ve yarın: yine sen.'],photo:['Hikâyemizin en güzel sayfalarından biri.'],song:['Bizim şarkımız','Bizi en başa götüren o şarkı.']},valentine:{postcard:['Kalbimin en güzel yerine…','Seni bir gün değil, her gün seviyorum.'],text:['Her gün, yeniden sen.'],photo:['Bu fotoğrafta en sevdiğim şey: biz.'],song:['Kalbimin şarkısı','Sana söyleyemediğimi bu şarkı söylesin.']},promotion:{postcard:['Seninle gurur duyuyorum.','Emeklerinin karşılığını aldığını görmek çok güzel.'],text:['Bunu sen yaptın. Ve daha yeni başlıyorsun.'],photo:['Başarı sana çok yakışıyor.'],song:['Zafer şarkın','Bu başarıyı kutlarken bize eşlik etsin.']},just:{postcard:['Bugün aklıma sen geldin.','Seni düşünmek için özel bir güne ihtiyacım yok.'],text:['İyi ki hayatımdasın. Hepsi bu.'],photo:['Bu anı bugün yeniden hatırlamak istedim.'],song:['Bugünün şarkısı','Dinlerken sana göndermek istedim.']},special:{postcard:['Sana özel bir not…','Bu kutunun sebebi sadece bize özel.'],text:['Bunu anlatmanın tek bir başlığı yok.'],photo:['Bu kareyi burada saklamak istedim.'],song:['Bu ana özel','Bu şarkı kutunun hikâyesine eşlik etsin.']}};
const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let box={theme:'love',recipient:'',sender:'',title:'',note:'',finalNote:'',items:[],style:{...styleDefaults}},editing=null,pendingPhoto='',busy=false,saveTimer,toastTimer,restored=false,sharedLink='';
const newId=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
function spotifyLink(input){try{const u=new URL(input.trim());if(u.protocol!=='https:'||u.hostname!=='open.spotify.com')return null;const m=u.pathname.match(/^\/(?:intl-[a-z]{2}\/)?(track|album|playlist)\/([a-zA-Z0-9]{22})\/?$/);return m?{url:`https://open.spotify.com/${m[1]}/${m[2]}`,embed:`https://open.spotify.com/embed/${m[1]}/${m[2]}`} : null;}catch{return null;}}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3500);}
function validBox(data){if(!data||!themes.some(t=>t.id===data.theme)||!Array.isArray(data.items)||data.items.length>16)return false;return ['recipient','sender','title','note'].every(k=>typeof data[k]==='string')&&(!data.finalNote||typeof data.finalNote==='string')&&data.items.every(i=>i&&labels[i.type]&&typeof i.id==='string'&&(!i.photo||/^data:image\/(jpeg|png|webp);base64,[a-zA-Z0-9+/=]+$/.test(i.photo)||/^\/api\/boxes\/[A-Za-z0-9_-]+\/photos\/[A-Za-z0-9_-]+$/.test(i.photo))&&(i.type!=='song'||spotifyLink(i.url)));}
try{const stored=JSON.parse(localStorage.getItem('sakli-box-v1')||'null');if(validBox(stored)){box={...stored,finalNote:stored.finalNote||'',style:{...styleDefaults,...(stored.style||{})}};restored=true;}}catch{}
function save(){sharedLink='';$('sharePanel').hidden=true;clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem('sakli-box-v1',JSON.stringify(box));$('saveState').textContent='✓ Taslak bu tarayıcıda kaydedildi.';}catch{$('saveState').textContent='Tarayıcıya kaydedilemedi. Sayfayı kapatmadan önce bağlantı oluştur.';}},250);}
function theme(){return themes.find(t=>t.id===box.theme)||themes[0];}
function applyTheme(){const t=theme(),p=palettes[box.style.palette]||palettes.theme;document.documentElement.style.setProperty('--soft',p.soft||t.bg);document.documentElement.style.setProperty('--wine',p.wine||(t.id==='valentine'?'#873653':t.ink));$('themeTitle').textContent=t.name;$('themeBadge').textContent=(box.style.icon||t.symbol)+' '+t.name;renderStyleControls();}
function renderStyleControls(){const groups={paletteOptions:Object.entries(palettes).map(([value,p])=>({value,label:p.name,swatch:p.soft||theme().bg})),iconOptions:['♡','✦','☀','∞','✿'].map(value=>({value,label:value})),fontOptions:[{value:'romantic',label:'Romantik'},{value:'modern',label:'Sade'},{value:'hand',label:'El yazısı'}],layoutOptions:[{value:'collage',label:'Kolaj'},{value:'grid',label:'Düzenli'}],effectOptions:[{value:'hearts',label:'Kalpler'},{value:'stars',label:'Yıldızlar'},{value:'confetti',label:'Konfeti'},{value:'none',label:'Sade'}]};for(const [id,options] of Object.entries(groups)){const key=id.replace('Options','');$(id).innerHTML=options.map(o=>'<button type="button" data-style="'+key+'" data-value="'+escapeHTML(o.value)+'" class="'+(box.style[key]===o.value?'selected':'')+'"'+(o.swatch?' style="--swatch:'+o.swatch+'"':'')+'>'+(o.swatch?'<i></i>':'')+escapeHTML(o.label)+'</button>').join('');}}
for(const id of ['paletteOptions','iconOptions','fontOptions','layoutOptions','effectOptions'])$(id).onclick=e=>{const button=e.target.closest('[data-style]');if(!button)return;box.style[button.dataset.style]=button.dataset.value;applyTheme();save();};
function show(view){for(const id of ['choose','editor','preview'])$(id).hidden=id!==view;window.scrollTo({top:0,behavior:'instant'});}
function openEditor(){applyTheme();for(const [id,key] of [['recipient','recipient'],['sender','sender'],['boxTitle','title'],['coverNote','note'],['finalNote','finalNote']])$(id).value=box[key]||'';renderItems();show('editor');}
$('concepts').innerHTML=themes.map((t,i)=>`<button class="concept" data-theme="${t.id}" style="--tile:${t.bg};--tileink:${t.ink}"><span class="symbol" aria-hidden="true">${t.symbol}</span><span class="number">0${i+1}</span><h3>${t.name}</h3><p>${t.subtitle}</p><span class="arrow" aria-hidden="true">↗</span></button>`).join('');
$('concepts').onclick=e=>{const b=e.target.closest('[data-theme]');if(!b)return;const previous=theme();box.theme=b.dataset.theme;if(!box.title||box.title===previous.title)box.title=theme().title;if(box.style.palette==='theme')applyTheme();save();openEditor();};
$('myDraft').onclick=()=>{if(!box.title)box.title=theme().title;openEditor();};$('myDraft').textContent=restored?'Taslağıma dön ↗':'Kutuma başla ↗';$('backConcept').onclick=()=>show('choose');
for(const [id,key] of [['recipient','recipient'],['sender','sender'],['boxTitle','title'],['coverNote','note'],['finalNote','finalNote']])$(id).oninput=e=>{box[key]=e.target.value;save();};
function memoryMarkup(item,gift=false){const title=escapeHTML(item.title),text=escapeHTML(item.text);let content='';if(item.type==='postcard')content=`<span class="stamp" aria-hidden="true">${theme().symbol}</span><h3>${title}</h3><p>${text}</p>`;if(item.type==='text')content=`<div class="shape"><p>${text}</p></div>`;if(item.type==='photo')content=`<img src="${escapeHTML(item.photo)}" alt="${title||'Birlikte bir anı'}"><p>${title}</p>`;if(item.type==='song')content=`<span class="musicicon" aria-hidden="true">♫</span><small>BİZİM ŞARKIMIZ</small><h3>${title||'Sana bir şarkı'}</h3><p>${text}</p>${gift?`<button class="spotify-open" data-spotify="${escapeHTML(spotifyLink(item.url)?.embed||'')}">Spotify'da dinle ▶</button>`:''}`;return `<div class="memory-body">${content}</div>`;}
function renderItems(){$('itemCount').textContent=box.items.length+' anı';$('items').innerHTML=box.items.length?box.items.map((item,i)=>`<article class="memory ${item.type} ${['heart','circle','wave'].includes(item.shape)?item.shape:''}"><button class="card-open" data-edit="${item.id}" aria-label="${escapeHTML(labels[item.type])} düzenle">${memoryMarkup(item)}</button><div class="cardfoot"><span>${String(i+1).padStart(2,'0')} / ${labels[item.type]}</span><div class="cardactions"><button data-move="${item.id}" data-dir="-1" ${i===0?'disabled':''} aria-label="Anıyı önceye taşı">←</button><button data-move="${item.id}" data-dir="1" ${i===box.items.length-1?'disabled':''} aria-label="Anıyı sonraya taşı">→</button><button data-delete="${item.id}" aria-label="Anıyı kaldır">×</button></div></div></article>`).join(''):'<div class="empty"><span>♡</span><h3>İlk anıyla başlasın.</h3><p>Yukarıdan bir kartpostal, not, fotoğraf veya şarkı ekle.</p></div>';}
$('items').onclick=e=>{const edit=e.target.closest('[data-edit]'),move=e.target.closest('[data-move]'),del=e.target.closest('[data-delete]');if(edit)return openItem(box.items.find(i=>i.id===edit.dataset.edit));if(move){const from=box.items.findIndex(i=>i.id===move.dataset.move),to=from+Number(move.dataset.dir);if(to>=0&&to<box.items.length){[box.items[from],box.items[to]]=[box.items[to],box.items[from]];renderItems();save();}}if(del){box.items=box.items.filter(i=>i.id!==del.dataset.delete);renderItems();save();toast('Anı kutudan kaldırıldı.');}};
document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{if(box.items.length>=16)return toast('Bir kutuya en fazla 16 anı ekleyebilirsin.');openItem({id:newId(),type:b.dataset.add,title:'',text:'',shape:'heart',url:'',photo:''},true);});
function openItem(item,isNew=false){editing={...item,isNew};pendingPhoto=item.photo||'';$('dialogTitle').textContent=labels[item.type]+(isNew?' ekle':' düzenle');$('formError').textContent='';$('saveItem').textContent=isNew?'Kutuya ekle ♡':'Değişiklikleri kaydet';let fields='';if(['postcard','song'].includes(item.type))fields+=`<label>${item.type==='song'?'Şarkının adı':'Kartın başlığı'}<input id="itemTitle" maxlength="80" value="${escapeHTML(item.title)}" placeholder="${item.type==='song'?'Bize hep o günü hatırlatan şarkı':'Sende en sevdiğim şey…'}" required></label>`;if(item.type==='photo')fields+=`<label>Bir fotoğraf seç<input id="itemPhoto" type="file" accept="image/jpeg,image/png,image/webp,image/avif" ${pendingPhoto?'':'required'}></label><p class="dialoghint">JPG, PNG, WebP veya AVIF · En fazla 12 MB. Fotoğraf kutuya uygun boyuta küçültülür.</p><img class="uploadpreview" id="photoPreview" ${pendingPhoto?`src="${escapeHTML(pendingPhoto)}"`:'hidden'} alt="Seçilen fotoğraf"><label>Altına bir not<input id="itemTitle" maxlength="100" value="${escapeHTML(item.title)}" placeholder="O gün hiç bitmesin istemiştim."></label>`;if(item.type==='text')fields+=`<label>Yazının şekli<select id="itemShape"><option value="heart">Yumuşak kalp</option><option value="circle">Yuvarlak</option><option value="wave">Dalga</option></select></label>`;if(item.type!=='photo')fields+=`<label>${item.type==='song'?'Bu şarkı neden burada?':'İçinden geçenler'}<textarea id="itemText" rows="4" maxlength="${item.type==='text'?180:700}" placeholder="Sadece senin söyleyebileceğin bir şey yaz…" ${item.type==='song'?'':'required'}>${escapeHTML(item.text)}</textarea></label>`;if(item.type==='song')fields+=`<label>Spotify bağlantısı<input id="itemUrl" type="url" value="${escapeHTML(item.url)}" placeholder="https://open.spotify.com/track/…" required></label><p class="dialoghint">Spotify’da şarkı → Paylaş → Bağlantıyı kopyala. Şarkı, albüm ve çalma listesi bağlantıları desteklenir. Çalma süresi Spotify hesabına ve bölgeye bağlı olabilir.</p>`;$('itemFields').innerHTML=fields;if(item.type==='text')$('itemShape').value=item.shape||'heart';if(item.type==='photo')$('itemPhoto').onchange=readPhoto;$('ideaButton').hidden=!isNew;$('itemDialog').showModal();}
$('ideaButton').onclick=()=>{if(!editing)return;const ideas=ideaBank[box.theme]||ideaBank.just,idea=ideas[editing.type];if(!idea)return;if(editing.type==='postcard'){if($('itemTitle'))$('itemTitle').value=idea[0];if($('itemText'))$('itemText').value=idea[1];}else if(editing.type==='song'){if($('itemTitle'))$('itemTitle').value=idea[0];if($('itemText'))$('itemText').value=idea[1];}else if($('itemTitle'))$('itemTitle').value=idea[0];else if($('itemText'))$('itemText').value=idea[0];toast('Bir başlangıç bıraktım; istersen tamamen değiştir.');};
async function readPhoto(e){const file=e.target.files[0];if(!file)return;const session=editing;busy=true;$('saveItem').disabled=true;$('formError').textContent='Fotoğraf hazırlanıyor…';let url;try{if(!['image/jpeg','image/png','image/webp','image/avif'].includes(file.type)||file.size>12*1024*1024)throw Error('12 MB altında bir JPG, PNG, WebP veya AVIF seç.');url=URL.createObjectURL(file);const img=new Image();img.src=url;await img.decode();if(img.naturalWidth*img.naturalHeight>50e6)throw Error('Fotoğraf çok büyük. Daha küçük bir görsel seç.');const scale=Math.min(1,1400/Math.max(img.naturalWidth,img.naturalHeight)),c=document.createElement('canvas');c.width=Math.round(img.naturalWidth*scale);c.height=Math.round(img.naturalHeight*scale);const context=c.getContext('2d');context.fillStyle='#fff';context.fillRect(0,0,c.width,c.height);context.drawImage(img,0,0,c.width,c.height);if(editing!==session)return;pendingPhoto=c.toDataURL('image/jpeg',.8);$('photoPreview').src=pendingPhoto;$('photoPreview').hidden=false;$('formError').textContent='';}catch(error){if(editing===session){$('formError').textContent=error.message||'Fotoğraf açılamadı.';e.target.value='';}}finally{if(url)URL.revokeObjectURL(url);if(editing===session){busy=false;$('saveItem').disabled=false;}}}
function closeItem(){editing=null;busy=false;$('saveItem').disabled=false;$('itemDialog').close();}for(const id of ['closeDialog','cancelDialog'])$(id).onclick=closeItem;$('itemDialog').addEventListener('cancel',()=>{editing=null;busy=false;$('saveItem').disabled=false;});
$('itemForm').onsubmit=e=>{e.preventDefault();if(busy||!editing)return;const item={id:editing.id,type:editing.type,title:$('itemTitle')?.value.trim()||'',text:$('itemText')?.value.trim()||'',shape:$('itemShape')?.value||'heart',photo:pendingPhoto,url:''};if(item.type==='photo'&&!pendingPhoto){$('formError').textContent='Önce bir fotoğraf seç.';return;}if(['postcard','text'].includes(item.type)&&!item.text){$('formError').textContent='Anın için birkaç kelime yaz.';return;}if(item.type==='song'){const link=spotifyLink($('itemUrl').value);if(!link){$('formError').textContent='Geçerli bir open.spotify.com şarkı, albüm veya çalma listesi bağlantısı gir.';return;}item.url=link.url;}if(editing.isNew)box.items.push(item);else{const index=box.items.findIndex(i=>i.id===item.id);if(index>=0)box.items[index]=item;}save();renderItems();closeItem();toast('Anın kutudaki yerini aldı. ♡');};
function giftMarkup(){const style=box.style||styleDefaults;return `<div class="gift-shell font-${escapeHTML(style.font)} layout-${escapeHTML(style.layout)}" data-effect="${escapeHTML(style.effect||'hearts')}"><div class="gift-to">${escapeHTML(box.recipient||'Sevdiğime')} için, sevgiyle</div><h1>${escapeHTML(box.title||theme().title)}</h1><p class="gift-note">${escapeHTML(box.note||'Bu kutuda biraz biz varız. İyi ki.')}</p><p class="gift-sign">Sevgiyle, ${escapeHTML(box.sender||'seni seven biri')}</p><button class="seal" data-open-gift aria-label="Anı kutusunu aç">${escapeHTML(style.icon||'♡')}</button><p class="opentext">KALBE DOKUN, KUTUYU AÇ</p><div class="surprise-layer" aria-hidden="true"></div><div class="gift-items" hidden>${box.items.map(item=>`<article class="memory ${item.type} ${['heart','circle','wave'].includes(item.shape)?item.shape:''}">${memoryMarkup(item,true)}</article>`).join('')}</div><p class="receipt" hidden>${escapeHTML(box.finalNote||'Hepsi bir yana, iyi ki sen. ♡')}</p></div>`;}
function celebrate(shell){const effect=shell.dataset.effect;if(effect==='none')return;const layer=shell.querySelector('.surprise-layer'),symbols=effect==='stars'?['✦','✧','⋆']:effect==='confetti'?['●','◆','■','▲']:['♡','♥','♡'];for(let i=0;i<22;i++){const bit=document.createElement('i');bit.textContent=symbols[i%symbols.length];bit.style.setProperty('--x',(8+Math.random()*84)+'%');bit.style.setProperty('--dx',(-90+Math.random()*180)+'px');bit.style.setProperty('--delay',(Math.random()*.35)+'s');bit.style.setProperty('--spin',(-90+Math.random()*180)+'deg');layer.appendChild(bit);}setTimeout(()=>layer.replaceChildren(),2300);}
function giftClick(e){const open=e.target.closest('[data-open-gift]');if(open){const shell=open.closest('.gift-shell');shell.querySelector('.gift-items').hidden=false;shell.querySelector('.receipt').hidden=false;shell.querySelector('.opentext').hidden=true;open.hidden=true;celebrate(shell);return;}const play=e.target.closest('[data-spotify]');if(play){const src=play.dataset.spotify;if(!/^https:\/\/open\.spotify\.com\/embed\/(track|album|playlist)\/[a-zA-Z0-9]{22}$/.test(src))return;const frame=document.createElement('iframe');frame.title='Spotify şarkı oynatıcı';frame.src=src;frame.allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture';frame.loading='lazy';play.replaceWith(frame);}}
$('giftPreview').onclick=giftClick;$('sharedGift').onclick=giftClick;$('previewButton').onclick=()=>{if(!box.items.length)return toast('Önce kutuya en az bir anı ekle.');$('giftPreview').innerHTML=giftMarkup();show('preview');};$('backEditor').onclick=()=>show('editor');
async function copyShareLink(){try{await navigator.clipboard.writeText($('shareUrl').value);toast('Bağlantı kopyalandı. ♡');}catch{$('shareUrl').select();document.execCommand('copy');toast('Bağlantı kopyalandı. ♡');}}
$('copyLink').onclick=copyShareLink;
$('nativeShare').hidden=!navigator.share;$('nativeShare').onclick=async()=>{try{await navigator.share({title:box.title||'Sana saklı bir kutu',text:'Senin için küçük bir sürpriz hazırladım. ♡',url:$('shareUrl').value});}catch{}}
$('shareButton').onclick=async()=>{const button=$('shareButton');if(sharedLink){$('sharePanel').hidden=false;return;}button.disabled=true;button.textContent='Kutun hazırlanıyor…';try{const response=await fetch('/api/boxes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(box)}),data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||'Bağlantı oluşturulamadı.');sharedLink=new URL(data.url,location.origin).href;$('shareUrl').value=sharedLink;$('sharePanel').hidden=false;$('deliveryNote').textContent='Bağlantın hazır. Düzenleme yaparsan yeni bir bağlantı oluşturabilirsin.';toast('Kutun paylaşılmaya hazır. ♡');$('sharePanel').scrollIntoView({behavior:'smooth',block:'center'});}catch(error){toast(error.message||'Bağlantı oluşturulamadı. Biraz sonra tekrar dene.');}finally{button.disabled=false;button.textContent='Paylaşım linki oluştur ↗';}};

async function loadSharedBox(id){document.body.classList.add('shared-mode');for(const section of ['choose','editor','preview'])$(section).hidden=true;$('shared').hidden=false;$('myDraft').hidden=true;try{const response=await fetch('/api/boxes/'+encodeURIComponent(id));if(!response.ok)throw Error();const data=await response.json();if(!validBox(data))throw Error();box={...data,finalNote:data.finalNote||'',style:{...styleDefaults,...(data.style||{})}};applyTheme();document.title=(box.title||'Sana saklı bir kutu')+' — Saklı';$('sharedStatus').hidden=true;$('sharedGift').innerHTML=giftMarkup();}catch{$('sharedStatus').hidden=true;$('sharedError').hidden=false;}}
const sharedMatch=location.pathname.match(/^\/b\/([A-Za-z0-9_-]{16,64})\/?$/);if(sharedMatch)loadSharedBox(sharedMatch[1]);

